export const PHILIPPINES_HMO_PROVIDERS = [
  'Asiancare Multi-Purpose Cooperative',
  'Avega Managed Care',
  'AXA Philippines',
  'Carewell Health Systems, Inc.',
  'Cocolife (COCOLIFE)',
  'Cooperative Health Management Federation (CHMF)',
  'Dynamic Care Corporation',
  'EastWest Healthcare, Inc.',
  'Generali Philippines',
  'Getwell Health Systems, Inc.',
  'Health Care and Development Corporation of the Philippines (HDCP)',
  'Health Delivery System (HDS)',
  'Health Maintenance, Inc. (HMI)',
  'HPPI (Health Partners Philippines, Inc.)',
  'I-Care Health Sciences, Inc.',
  'Insular Life',
  'Intellicare (Asalus Corporation)',
  'Kaiser Medical Center Foundation, Inc.',
  'Lifeline 16911 Medical, Inc.',
  'Lifeline Medical, Inc.',
  'Manulife Philippines',
  'Maxicare Healthcare Corporation',
  'MediCard Lifestyle',
  'MediCard Philippines, Inc.',
  'MediCard Select (Select Healthcare Systems)',
  'Other / Not Listed',
  'Pacific Cross Health Care, Inc.',
  'PhilCare (Philhealthcare, Inc.)',
  'Prudential Life',
  "St. Luke's Extended Care Services, Inc. (SL-EXOS)",
  'Sun Life Grepa Financial',
  'ValuCare Health Systems, Inc.',
  'Wellnet Healthcare Systems, Inc.',
];