/** Major HMO / health plan brands in the Philippines (display + validation). */
export const PHILIPPINES_HMO_PROVIDERS = [
  'Asiancare Multi-Purpose Cooperative',
  'Avega (Avega Managed Care)',
  'Carewell Health Systems',
  'Cooperative Health Management Federation (CHMF)',
  'Cooperative Health Management Federation (Philhealthcare)',
  'Dynamic Care Corporation',
  'EastWest Healthcare',
  'Getwell Health Systems',
  'Health Care and Development Corporation of the Philippines (HDCP)',
  'Health Delivery System (HDS)',
  'Health Maintenance, Inc. (HMI)',
  'HPPI (Health Partners Philippines, Inc.)',
  'I-Care Health Sciences, Inc.',
  'Intellicare / Asalus Corporation',
  'Kaiser Medical Center Foundation, Inc.',
  'Lifeline Medical, Inc.',
  'Lifeline 16911 Medical, Inc.',
  'Maxicare Healthcare Corporation',
  'Medicard Philippines, Inc.',
  'MediCard Select / Select Healthcare Systems',
  'Medilink Health Care Systems, Inc.',
  'MEDICard Lifestyle',
  'Pacific Cross Health Care, Inc.',
  'PhilCare (Philhealthcare, Inc.)',
  'St. Luke\'s Extended Care Services, Inc. (SL-EXOS)',
  'ValuCare Health Systems, Inc.',
  'Wellnet Healthcare Systems, Inc.',
  'Other / not listed',
];
